name: Question
description: If you need help understanding or using our tool
title: "<title>"
labels: ["question", "triage"]
assignees:
  - mliberty1
body:
  - type: dropdown
    id: Joulescope-model
    attributes:
      label: Joulescope model
      description: Enter the Joulescope model connected to your computer.
      multiple: true
      options:
        - JS220
        - JS110
        - other
  - type: dropdown
    id: version
    attributes:
      label: UI version
      description: What version of our software are you running?
      options:
        - 1.1.12
        - 1.1.11
        - other
    validations:
      required: true
  - type: textarea
    id: Question
    attributes:
      label: Your question
      placeholder: How to ...
    validations:
      required: true
  - type: dropdown
    id: Environment
    attributes:
      label: What OS are you using?
      description: You can select multiple OS
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Windows 7
        - macOS 14 arm64 (M1 and newer)
        - macOS 14 amd64
        - macOS 13 arm64 (M1 and newer)
        - macOS 13 amd64
        - macOS 12 arm64 (M1 and newer)
        - macOS 12 amd64
        - macOS 11 amd64
        - macOS 10
        - Linux Ubuntu amd64 (PC)
        - Linux Ubuntu arm64 (Raspberry Pi 4)
        - Other (describe below)
